### ISSUE TITLE
Add this workbench to FreeCAD-addons

### ISSUE THREAD

**Issue by luzpaz** [FredsFactory/FreeCAD_AirPlaneDesign#1]
https://github.com/FreeCAD/FreeCAD-addons

**Comment by FredsFactory** [comment]
Hello 
Yes of course, but I doesn't know the process to publish my first version in the FreeCAD AddOn repository! I'll take care of it as soon as I finish a first version.

Frederic

**Comment by luzpaz** [comment]
Added to FreeCAD-addons in https://github.com/FreeCAD/FreeCAD-addons/commit/85549d3cdb967deee6228ff2ce687447e979e434
