### ISSUE TITLE
Provide english descriptions for the AirPlaneData data sheet Names column fields

### ISSUE THREAD

**Issue by tombelpasso** [FredsFactory/FreeCAD_AirPlaneDesign#10]
There are many names in the column which I have no idea what mean.

Thanks.

**Comment by FredsFactory** [comment]
Thank for your issue. I integrate some English translation in the table sheet. Update the workbench and init a new plane. Sorry for the delay I'm very busy for the moment, I will spend more time on this development in April.  
Frederic

**Comment by luzpaz** [comment]
Any progress on this ?

**Comment by FredsFactory** [comment]
Done, some new instructions in the readme file.
