### ISSUE TITLE
OpenGlider GUI for FreeCAD (similar add-on)

### ISSUE THREAD

**Issue by ghost** [FredsFactory/FreeCAD_AirPlaneDesign#2]
Look on "FreeCAD Glider" add-on:

- https://github.com/booya-at/freecad_glider

Maybe, you will try cooperate with @booya-at for improving your and his add-ons ;-)

**Comment by FredsFactory** [comment]
Thanks for information, but I think it's not the same goal..booya-at build paraglider wing. In my case the goal is to facilitate the design of RC Glider or RC Plane.
