### ISSUE TITLE
How to Add/Remove Panels in Create A Wing Dialog

### ISSUE THREAD

**Issue by rickpalo** [FredsFactory/FreeCAD_AirPlaneDesign#29]
In your Create a Wing dialog, how can I add or remove panels?  I can get the example 5 panels, but don't understand how to add or remove a panel.  
Thank you!
![AirplaneDesign_dialog](https://user-images.githubusercontent.com/38861886/78723487-bd2fe580-78e8-11ea-8c43-e559370cb7d7.png)

**Comment by FredsFactory** [comment]
Hello, I added two buttons one to add row and another to delete existing row. 
Thanks for your comment.
Fred

<img width="1056" alt="Capture d’écran 2020-04-08 à 22 41 20" src="https://user-images.githubusercontent.com/34234759/78831891-b12c4c80-79ea-11ea-81f8-21ee04eb0e86.png">

**Comment by rickpalo** [comment]
That works great!  Thanks for the quick response!!
