### ISSUE TITLE
Updating AirPlaneDesign WB to be compatible with the upcoming 0.18 release (req. py3 and Qt5 compatibility)

### ISSUE THREAD

**Issue by luzpaz** [FredsFactory/FreeCAD_AirPlaneDesign#3]
ref: https://github.com/FreeCAD/FreeCAD-addons/issues/93

**Comment by luzpaz** [comment]
Hey @FredsFactory hows the progress going for this?

**Comment by FredsFactory** [comment]
In progress, first feature is OK : generate wing.

**Comment by FredsFactory** [comment]
In progress, second feature is OK : generate wing ribs.

**Comment by FredsFactory** [comment]
Last test on Windows 10 : ok
