### ISSUE TITLE
Does this Workbench have a logo/icon?

### ISSUE THREAD

**Issue by luzpaz** [FredsFactory/FreeCAD_AirPlaneDesign#5]
In regards to https://freecadweb.org/wiki/Template:DevWorkbenches

**Comment by FredsFactory** [comment]
Now yes. 8-)

**Comment by luzpaz** [comment]
Discussion on the FC UI/UX subforum about this issue: https://forum.freecadweb.org/viewtopic.php?f=34&t=31376
