### ISSUE TITLE
Ignoring the .git/ in a .gitignore file

### ISSUE THREAD

**Issue by luzpaz** [FredsFactory/FreeCAD_AirPlaneDesign#8]
I noticed that you have the .git/ folder. I'm not sure it's necessary to upload that to Github. Checkout out:  
https://stackoverflow.com/questions/34618950/git-ignore-git-folder

**Comment by FredsFactory** [comment]
done.

**Comment by luzpaz** [comment]
Cool. 
FYI, did you know about this: https://www.freecadweb.org/wiki/Artwork_Guidelines
