### ISSUE TITLE
New logo for workbench

### ISSUE THREAD

**Issue by luzpaz** [FredsFactory/FreeCAD_AirPlaneDesign#9]
![image](https://user-images.githubusercontent.com/4140247/46620333-734b2100-caf2-11e8-9df3-ead19afda79e.png)
Props to @bitacovir
ref: https://forum.freecadweb.org/viewtopic.php?f=34&t=31376&p=260625&hilit=airplanedesign#p260625

**Comment by FredsFactory** [comment]
New Icon pushed in git..
Thanks
